spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  config:
    import: file:./src/main/resources/config/secret.yml

server:
  port: 8000
